name: Update pnpm (corepack)

on:
    schedule:
        - cron: '10 * * * 1-5'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update-pnpm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                run_install: true

            -   name: Install Node.js
                uses: actions/setup-node@v6
                with:
                    node-version-file: .nvmrc
                    cache: 'pnpm'

            - name: Enable Corepack
              run: corepack enable

            - name: Update pnpm via Corepack
              run: corepack up

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              with:
                  branch: chore/update-pnpm
                  delete-branch: true
                  commit-message: "chore: update pnpm via corepack"
                  title: "chore: update pnpm (corepack)"
                  body: |
                      pnpm was updated using `corepack up pnpm`.

                      The `packageManager` field was updated automatically.
                  labels: |
                      ci
                      dependencies
